<?php 
return [
    'webinstaller.h1' => '后台管理系统',
    'webinstaller.install_complete' => '安装完成',
    'webinstaller.congratulations' => 'Congratulations! The application has been installed successfully.',
    'webinstaller.install_redirect' => 'Installation successful. Redirecting to the homepage in 5 seconds.',
    'webinstaller.manual_redirect' => 'Go to homepage now',
    'webinstaller.env_check' => 'Environment Check',
    'webinstaller.current_controller_prefix' => 'Current controller_resource_prefix',
    'webinstaller.item' => 'Item',
    'webinstaller.status' => 'Status',
    'webinstaller.redis_config' => 'Redis Config',
    'webinstaller.follow_main_application' => 'Follow Main Application',
    'webinstaller.no_redis_in_root' => 'Main application has no redis configured.',
    'webinstaller.no_database_in_root' => 'Main application has no database configured.',
    'webinstaller.host' => 'Host',
    'webinstaller.port' => 'Port',
    'webinstaller.auth' => 'Auth',
    'webinstaller.select' => 'Select',
    'webinstaller.multi_redis_hint' => 'Multiple redis configs are supported: add more entries to the config file manually after install.',
    'webinstaller.database_config' => 'Database Config',
    'webinstaller.driver' => 'Driver',
    'webinstaller.file' => 'File',
    'webinstaller.dbname' => 'Database',
    'webinstaller.username' => 'Username',
    'webinstaller.password' => 'Password',
    'webinstaller.multi_db_hint' => 'Multiple database configs (master/slave) are supported: add more entries to the config file manually after install.',
    'webinstaller.force_reinstall' => 'Force reinstall (drop existing tables)',
    'webinstaller.customer_setting' => 'Customer Setting',
    'webinstaller.install' => '安装',

    'Admin Name' => '管理员账号',
    'Admin Password' => '管理员密码',
    'Admin Password Confirm' => '确认密码',
];


